# This is a basic workflow to help you get started with Actions

name: build bionic kernel

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: bionic build job
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt update && sudo apt install git fakeroot
      - name: code
        run: mkdir ~/kbuild && cd ~/kbuild && git clone --depth=1 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/bionic -b hwe-edge
      - name: build
        run: cd ~/kbuild/bionic && LANG=C fakeroot debian/rules clean && LANG=C fakeroot debian/rules binary-headers binary-generic binary-perarch

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ====================================
          echo ok
